name: Flutter Build CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.9'
          java-package: jdk
          architecture: x64
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: build apk
        run: |
          flutter pub get
          flutter build apk
      - name: build ios
        run: |
          flutter pub get
          flutter build ios --release --no-codesign